// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdeToPokemon.Data;

namespace OdeToPokemon.Data.Migrations
{
    [DbContext(typeof(OdeToPokemonDbContext))]
    partial class OdeToPokemonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OdeToPokemon.Core.Pokemon", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80);

                    b.Property<int>("Id");

                    b.Property<string>("NextEvolutionName");

                    b.Property<int>("Type");

                    b.HasKey("Name");

                    b.HasIndex("NextEvolutionName")
                        .IsUnique()
                        .HasFilter("[NextEvolutionName] IS NOT NULL");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("OdeToPokemon.Core.Pokemon", b =>
                {
                    b.HasOne("OdeToPokemon.Core.Pokemon", "NextEvolution")
                        .WithOne("PreviousEvolution")
                        .HasForeignKey("OdeToPokemon.Core.Pokemon", "NextEvolutionName");
                });
#pragma warning restore 612, 618
        }
    }
}
